chatbot/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import SignUpView, CustomLoginView

app_name = 'common'

urlpatterns = [
    path('login/', CustomLoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('kakao/login', views.kakao_login, name='kakao_login'),
    path('kakao/login/callback', views.kakao_login_callback, name='kakao_login_callback'),
    path('profile/', views.profile_view, name='profile'),
]

chatbot/common/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.contrib.auth.models import Group, Permission

# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.username = email  # username 필드에 이메일 값을 사용
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    # related_name을 추가하여 충돌을 해결
    groups = models.ManyToManyField(
        Group,
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        related_name="custom_user_set",
        related_query_name="user",
    )
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name="custom_user_set",
        related_query_name="user",
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

chatbot/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
import re

User = get_user_model()

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import re

User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)  # 명시적으로 email 필드 추가

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('email',)  # email 필드만 사용

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not re.match(r"[^@]+@[^@]+\.[^@]+", email):
            raise ValidationError(_("유효한 이메일 주소를 입력해주세요."))
        if User.objects.filter(email=email).exists():
            raise ValidationError(_("이미 사용 중인 이메일 주소입니다."))
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = self.cleaned_data['email']  # username 필드에 email 값을 할당
        if commit:
            user.save()
        return user


class CustomAuthenticationForm(AuthenticationForm):
    pass

chatbot/common/views.py
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.contrib import messages
from django.views.generic.edit import CreateView
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy

from .forms import CustomUserCreationForm, CustomAuthenticationForm
from .models import User
import os
import requests
import json

User = get_user_model()
# Create your views here.


def logout_view(request):
    logout(request)
    return redirect('chat_app:chat')

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('chat_app:chat')
    template_name = 'common/signup.html'
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.save()  # 사용자 객체를 데이터베이스에 저장합니다.
        login(self.request, user)  # 사용자를 로그인 상태로 만듭니다.
        return redirect(self.get_success_url())  # 로그인 후 리다이렉트할 페이지로 이동합니다.
    
class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = 'common/login.html'

def kakao_login(request):
    KAKAO_AUTH_URL = 'https://kauth.kakao.com/oauth/authorize'
    KAKAO_REDIRECT_URI='http://43.201.236.125/common/kakao/login/callback'
    KAKAO_REST_API_KEY= os.getenv('KAKAO_REST_API_KEY')
    
    kakao_auth_url = f"{KAKAO_AUTH_URL}?client_id={KAKAO_REST_API_KEY}&redirect_uri={KAKAO_REDIRECT_URI}&response_type=code"
    return redirect(kakao_auth_url)

def kakao_login_callback(request):
    code = request.GET.get('code')
    KAKAO_TOKEN_URL = 'https://kauth.kakao.com/oauth/token'
    KAKAO_REDIRECT_URI='http://43.201.236.125/common/kakao/login/callback'
    
    token_request = requests.post(
        KAKAO_TOKEN_URL,
        data={
            'grant_type': 'authorization_code',
            'client_id': os.getenv('KAKAO_REST_API_KEY'),
            'redirect_uri': KAKAO_REDIRECT_URI,
            'code': code,
        },
    )
    token_json = token_request.json()
    error = token_json.get('error', None)
    if error is not None:
        # 토큰 요청 실패 처리
        print("Token request failed")
        return redirect('error_page')
    
    access_token = token_json.get("access_token")
    profile_request = requests.get("https://kapi.kakao.com/v2/user/me", headers={"Authorization": f"Bearer {access_token}"})
    
    profile_json = profile_request.json()
    print(json.dumps(profile_json, indent=4, ensure_ascii=False))
    kakao_account = profile_json.get('kakao_account', {})
    email = kakao_account.get('email')
    profile = kakao_account.get('profile', {})
    nickname = profile.get('nickname', 'User')  # 기본값 'User' 설정

    if not email:
        # 이메일이 없는 경우 닉네임 기반으로 이메일 생성
        email = f"{nickname}@kakao.com"

    user, created = User.objects.get_or_create(email=email, defaults={'username': email})
    if created:
        # 신규 생성된 사용자의 경우, 추가 설정을 진행합니다.
        user.set_unusable_password()  # 소셜 로그인이므로 패스워드 설정 불필요
        user.save()

    login(request, user, backend='django.contrib.auth.backends.ModelBackend')

    # 로그인 후 리다이렉트할 페이지. 'chat_app:chat'는 예시 URL 패턴 이름입니다.
    return redirect(reverse('chat_app:chat'))

@login_required  
def profile_view(request):
    return render(request, 'common/profile.html') 

chatbot/templates/common/base_common.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="{% static '/css/style.css' %}" rel="stylesheet">
  <link href="{% static '/css/sign.css' %}" rel="stylesheet">
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
  <script src="https://developers.kakao.com/sdk/js/kakao.min.js"></script>
  <title>{% block title %}{% endblock %}</title>
  {% block styles %}{% endblock %}
</head>
<body>
{% block content %}{% endblock %}
<script type="text/javascript" src="{% static 'javascript/login.js' %}"></script>
<script type="text/javascript" src="{% static 'javascript/interaction.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

chatbot/templates/common/login.html
{% extends 'common/base_common.html' %}
{% block title %}Dr.RC{% endblock %}
{% load static %}  <!-- 정적 파일 태그를 사용하기 위해 필요합니다. -->
{% block styles %}
{% endblock %}
{% block content %}
<div class="main-container">
    <div class="outer-container">
        <br><br>
        <div class="content">Dr.RC는 누구나 무료로 <br>질문할 수 있는 실시간 <br>의료 상담 AI 챗봇입니다</div>
        <br>
        <div class="circle-group">
            <div class="decorative-circle large"></div>
            <div class="decorative-circle medium"></div>
            <div class="decorative-circle small"></div>
        </div>
    </div>
    <div class="container">
        <br>
        <div style="width: 100%; height: 100%; flex-direction: column; justify-content: flex-start; align-items: center; gap: 6px; display: inline-flex">
            <div style="text-align: center; color: #878D96; font-size: 16px; font-family: Pretendard; font-weight: 400; line-height: 24px; word-wrap: break-word">로그인 하고 Dr.RC를 무료로 시작해보세요</div>
            <div style="text-align: center; color: #212B36; font-size: 33px; font-family: Pretendard; font-weight: 700; line-height: 45px; word-wrap: break-word">로그인</div>
        </div>
        <form class="form-container" action="{% url 'common:login' %}" method="post">
            {% csrf_token %}
            <div class="input-group {% if form.username.errors %}has-error{% endif %}">
                <label for="username">Email</label>
                <input type="text" name="username" id="username" placeholder="사용하실 이메일을 입력하세요" class="{% if form.username.errors %}input-error{% endif %}" value="{{ form.username.value|default_if_none:'' }}">
                {% for error in form.username.errors %}
                    <span class="error-message">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="input-group {% if form.password.errors %}has-error{% endif %}">
                <label for="password">Password</label>
                <input type="password" name="password" id="password" placeholder="사용하실 비밀번호를 입력하세요" class="{% if form.password.errors %}input-error{% endif %}">
                {% for error in form.password.errors %}
                    <span class="error-message">{{ error }}</span>
                {% endfor %}
            </div>
            {% if form.non_field_errors %}
                <div class="error-message">
                    {% for error in form.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            {% endif %}
            <div class="section" style="flex-direction: column;">
                <button type="submit" class="button">이메일로 로그인 하기</button>
                <div style="width: 380px; justify-content: center; align-items: center; gap: 16px; display: flex">
                    <div style="flex-grow: 1; height: 1px; background-color: #C1C7CD;"></div>
                    <span style="color: #C1C7CD; font-size: 16px; font-weight: 400;">또는</span>
                    <div style="flex-grow: 1; height: 1px; background-color: #C1C7CD;"></div>
                </div>
                <a href="{% url 'common:kakao_login' %}" class="button alt kakao-login">
                    <img src="{% static 'images/kakao_talk.svg' %}" alt="Kakao" class="kakao-icon">
                    카카오톡으로 회원 로그인하기</a>
            </div>
            <div class="signup-reminder">
                <span style="color: #878D96">아직 계정이 없으신가요? </span><a href="{% url 'common:signup' %}" style="color: #1B212F;">회원 가입하기</a>
            </div>
        </form>
        
    </div>
</div>
{% endblock %}
{% block scripts %}
{% comment %} <script type="text/javascript" src="{% static 'javascript/interaction.js' %}"></script> {% endcomment %}
{% endblock %}

chatbot/templates/common/login2.html
{% extends "base.html" %}
{% block title %}Dr.RC{% endblock %}
{% load static %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control clickEvent" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control clickEvent" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary clickEvent" name="loginLogin">로그인</button>
        <a class="btn btn-primary clickEvent" href="{% url 'common:signup' %}" name="loginSignup">회원가입</a>
    </form>
</div>
{% endblock %}
{% block scripts %}
    <script type="text/javascript" src="{% static 'javascript/interaction.js' %}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const urlParams = new URLSearchParams(window.location.search);
            const message = urlParams.get('message');
        
            if (message === 'loginRequired') {
                alert('로그인이 필요합니다. 질문을 위해서 먼저 로그인해 주세요.');
            }
        });
    </script>
{% endblock %}

chatbot/templates/common/profile.html
{% extends 'base.html' %}
{% block title %}Dr.RC{% endblock %}
{% load static %}  <!-- 정적 파일 태그를 사용하기 위해 필요합니다. -->
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/map.css' %}">
{% endblock %}
{% block content %}
<div class="title-with-icon">
    <h1 class="page-title">마이페이지</h1>
</div>
<div class="map_wrap">
    <h1 class="page-title"> 미구현 페이지입니다</h1>
</div>
{% endblock %}
{% block scripts %}
    <script type="text/javascript" src="{% static 'javascript/map.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/interaction.js' %}"></script>
{% endblock %}

chatbot/templates/common/signup.html
{% extends 'common/base_common.html' %}
{% block title %}Dr.RC{% endblock %}
{% load static %}  <!-- 정적 파일 태그를 사용하기 위해 필요합니다. -->
{% block styles %}
{% endblock %}
{% block content %}
    <div class="main-container" style="display: flex; flex-direction: row; align-items: stretch;">
        <div class="outer-container">
            <br><br>
            <div class="content">Dr.RC는 누구나 무료로 <br>질문할 수 있는 실시간 <br>의료 상담 AI 챗봇입니다</div>
            <br>
            <div class="circle-group">
                <div class="decorative-circle large"></div>
                <div class="decorative-circle medium"></div>
                <div class="decorative-circle small"></div>
            </div>
        </div>
        <div class="container">
            <div style="width: 100%; height: 100%; flex-direction: column; justify-content: flex-start; align-items: center; gap: 6px; display: inline-flex">
                <div style="text-align: center; color: #878D96; font-size: 16px; font-family: Pretendard; font-weight: 400; line-height: 24px; word-wrap: break-word">시작해보세요</div>
                <div style="text-align: center; color: #212B36; font-size: 33px; font-family: Pretendard; font-weight: 700; line-height: 45px; word-wrap: break-word">회원가입</div>
            </div>
            <form class="form-container" action="{% url 'common:signup' %}" method="post">
                {% csrf_token %}
                <div class="input-group {% if form.email.errors %}has-error{% endif %}">
                    <label for="email">Email</label>
                    <input type="text" name="email" id="email" placeholder="사용하실 이메일을 입력하세요" class="{% if form.email.errors %}input-error{% endif %}" value="{{ form.email.value|default_if_none:'' }}">
                    {% for error in form.email.errors %}
                        <span class="error-message">{{ error }}</span>
                    {% endfor %}
                    {% if form.username.errors %}
                        {% for error in form.username.errors %}
                            <div class="error">{{ error }}</div>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="input-group {% if form.password1.errors %}has-error{% endif %}">
                    <label for="password">Password</label>
                    <input type="password" name="password1" id="password" placeholder="비밀번호를 입력하세요" class="{% if form.password1.errors %}input-error{% endif %}">
                    {% for error in form.password1.errors %}
                        <span class="error-message">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="input-group {% if form.password2.errors %}has-error{% endif %}">
                    <label for="password-confirm">Password Confirm</label>
                    <input type="password" name="password2" id="password-confirm" placeholder="비밀번호를 다시 한번 입력하세요" class="{% if form.password2.errors %}input-error{% endif %}">
                    {% for error in form.password2.errors %}
                        <span class="error-message">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="section" style="flex-direction: column;">
                    <button type="submit" class="button">이메일로 회원 가입하기</button>
                    <div style="width: 380px; justify-content: center; align-items: center; gap: 16px; display: flex">
                        <div style="flex-grow: 1; height: 1px; background-color: #C1C7CD;"></div>
                            <span style="color: #C1C7CD; font-size: 16px; font-weight: 400;">또는</span>
                        <div style="flex-grow: 1; height: 1px; background-color: #C1C7CD;"></div>
                    </div>
                    <a href="{% url 'common:kakao_login' %}" class="button alt kakao-login">
                        <img src="{% static 'images/kakao_talk.svg' %}" alt="Kakao" class="kakao-icon">
                        카카오톡으로 회원 가입하기
                    </a>
                </div>
                <div class="signup-reminder">
                    <span style="color: #878D96">계정이 이미 있으신가요? </span><a href="{% url 'common:login' %}" style="color: #1B212F;">로그인하기</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {% comment %} <script type="text/javascript" src="{% static 'javascript/interaction.js' %}"></script> {% endcomment %}
{% endblock %}

chatbot/templates/common/signup22.html
{% extends "base.html" %}
{% block title %}Dr.RC{% endblock %}
{% load static %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username" placeholder="이름을 입력해주세요"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1" placeholder="비밀번호를 입력해주세요"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2" placeholder="비밀번호를 한번 더 입력해주세요"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email" placeholder="이메일을 입력해주세요"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary clickEvent" name="singupSignup">가입하기</button>
    </form>
</div>
{% endblock %}
{% block scripts %}
    <script type="text/javascript" src="{% static 'javascript/interaction.js' %}"></script>
{% endblock %}