chatbot/api_app/urls.py
from django.urls import path
from . import views

app_name = 'api_app'

urlpatterns = [
    path('map/', views.map, name='map'),
    path('pedia/', views.pedia, name='pedia'),
    path('search/', views.search_from_naver, name='search_from_naver'),
    path('ask/', views.ask, name='ask'),
]

chatbot/chat_app/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from .views import log_interaction, get_user_chats, metrics, get_similar_answers

app_name = 'chat_app'

urlpatterns = [
    path("", views.chat, name="chat"),
    path("ask_question/", views.ask_question, name="ask_question"),
    path('log_interaction/', log_interaction, name='log_interaction'),
    path('api/get_user_chats/', get_user_chats, name='get_user_chats'),
    path('metrics/', metrics, name='metrics'),  # Prometheus 메트릭 엔드포인트 추가
    path('similar-answers/<int:question_id>/', get_similar_answers, name='get_similar_answers'),
]

chatbot/chatbot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("chat_app.urls")),
    path('common/', include('common.urls')),
    path('api_app/', include('api_app.urls')),
]

chatbot/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import SignUpView, CustomLoginView

app_name = 'common'

urlpatterns = [
    path('login/', CustomLoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('kakao/login', views.kakao_login, name='kakao_login'),
    path('kakao/login/callback', views.kakao_login_callback, name='kakao_login_callback'),
    path('profile/', views.profile_view, name='profile'),
]

chatbot/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/navbar.css' %}" rel="stylesheet">
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
  <title>{% block title %}{% endblock %}</title>
  {% block styles %}{% endblock %}
</head>
<body>
<!-- 네비게이션바 -->
<div class="max-w-full mx-auto flex flex-row justify-stretch overflow-hidden" style='height: 960px;'>
  {% include "navbar.html" %}
  <div class="flex flex-col w-full px-7 py-10">
    {% block content %}{% endblock %}
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script type="text/javascript" src="{% static 'javascript/interaction.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

chatbot/templates/chat_bot.html
{% extends 'base.html' %}
{% block title %}Dr.RC{% endblock %}
{% load static %}
{% block styles %}
<link href="{% static 'css/chatbot.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="flex flex-col md:flex-row justify-stretch items-start w-full">
        <div class="w-40">
            <a class="clickEvent" href="{% url 'chat_app:chat' %}" name="navbarMainPage">
                <span class="text-slate-900 text-3xl font-bold font-['Poppins']">Dr.</span>
                <span class="text-blue-600 text-3xl font-medium font-['Poppins']">RC</span>
            </a>
        </div>
    </div>
    <br>
    <div class="w-full h-[calc(100vh-10vh)] pt-10 bg-neutral-300 flex-col justify-end items-center flex overflow-hidden">
        <ul class="messages-list w-full overflow-auto px-5">
        <!-- 대화 목록을 담을 ul 요소 추가 -->
        </ul>
        <div class="loading-bar">
            <div class="loading-block"></div>
            <div class="loading-block"></div>
            <div class="loading-block"></div>
            <div class="loading-block"></div>
        </div>
    </div>
    <div class="self-stretch max-h-96 pl-11 py-1.5 flex-col justify-start items-start gap-3 flex overflow-auto"></div>
    <form class="message-form flex justify-between items-center w-full" id="message_input">
        {% csrf_token %}
        <div class="flex-grow flex-shrink basis-0 justify-start items-center gap-4 flex">
            <div class="flex-grow flex-shrink min-w-0 bg-black bg-opacity-10 rounded-lg">
                <textarea placeholder="메세지를 입력하세요" class="message-input w-full h-16 px-4 py-2.5 text-slate-900 bg-transparent text-opacity-50 text-xl font-medium leading-10" id='message-input'></textarea>
            </div>
        </div>
        <div class="flex justify-start items-start gap-3 mt-4 md:mt-0">
            <button type="submit" class="w-14 h-14 flex justify-center items-center">
                <svg width="54" height="55" viewBox="0 0 54 55" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <g id="ri-send-plane-fill" clip-path="url(#clip0_2_1752)">
                        <g id="Group">
                            <path id="Vector" d="M4.37838 21.6355C3.20388 21.244 3.19263 20.6117 4.40088 20.209L47.3466 5.89448C48.5369 5.49848 49.2186 6.16448 48.8856 7.32998L36.6141 50.2735C36.2766 51.4637 35.5904 51.5042 35.0864 50.3747L26.9999 32.1767L40.4999 14.1767L22.4999 27.6767L4.37838 21.6355Z" fill="#A6ADB5"/>
                        </g>
                    </g>
                    <defs>
                        <clipPath id="clip0_2_1752">
                            <rect width="54" height="54" fill="white" transform="translate(0 0.676758)"/>
                        </clipPath>
                    </defs>
                </svg>
            </button>
        </div>
    </form>
{% if messages %}
    <script>
        window.onload = function() {
            {% for message in messages %}
                alert("{{ message }}");
            {% endfor %}
        }
    </script>
{% endif %}

{% endblock %}
{% block scripts %}
    <script type="text/javascript" src="{% static 'javascript/chatbot.js' %}"></script>
    <script type="text/javascript">
        // Django 템플릿 태그를 사용하여 사용자의 로그인 상태를 확인합니다.
        var isLoggedIn = {% if user.is_authenticated %}true{% else %}false{% endif %};
    </script>
    <script type="text/javascript" src="{% static 'javascript/interaction.js' %}"></script>
{% endblock %}

chatbot/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

chatbot/templates/navbar.html
{% load static %} 

<div class="navbar w-96 px-5 pt-9 flex-col justify-stretch items-center gap-10 inline-flex flex">
    <div class="justify-start items-start gap-1 inline-flex">
    </div>
    <div class="flex-col justify-stretch gap-2 flex">
        {% if user.is_authenticated %}
        <div class="flex-col pt-3 justify-center items-center gap-10 inline-flex" style='height: 260px;'>
            <img class="w-40 h-40" src="{% static '/images/unknownUser.png' %}" alt="User Image" />
            <div class="text-slate-900 text-2xl font-medium font-['Poppins'] leading-normal">{{ user.username }}</div>
        </div>
        {% else %}
        <a href="{% url 'common:login' %}" class="flex-col justify-center items-center gap-4 inline-flex">
            <img class="w-40 h-40" src="{% static '/images/unknownUser.png' %}" alt="Unknown User" />
            <div class="text-slate-900 text-2xl font-medium font-['Poppins'] leading-normal">로그인이 필요합니다</div>
        </a>
        {% endif %}
        <div class="navbar-center w-full flex-row"> 
            {% if user.is_authenticated %}
                <a class="clickEvent button-custom" href="{% url 'common:logout' %}" name="navbarLogout" style="min-width: 85px;">
                    로그아웃
                </a>
                <a class="clickEvent button-custom" href="{% url 'common:profile' %}" name="navbarProfile" style="min-width: 93px;">
                    마이페이지
                </a>
            {% else %}
                <a class="clickEvent button-custom" href="{% url 'common:signup' %}" name="navbarSignup" style="min-width: 85px;">
                    회원가입
                </a>
                <a class="clickEvent button-custom" href="{% url 'common:login' %}" name="navbarLogin" style="min-width: 85px;">
                    로그인
                </a>
            {% endif %}
        </div>        
        <div class="flex-col justify-start items-start gap-11 flex">
            <div class="px-7 py-2.5 bg-blue-600 rounded-tr-3xl rounded-bl-2xl rounded-br-3xl shadow justify-center items-center gap-2.5 inline-flex">
                <div class="w-6 h-6 flex justify-center items-center">
                    <svg width="24" height="25" viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <g id="ri-message-3-fill" clip-path="url(#clip0_2_1638)">
                        <g id="Group">
                        <path id="Vector" d="M2 9.95348C1.99947 9.16569 2.15435 8.38552 2.45577 7.65767C2.75718 6.92981 3.19921 6.26856 3.75655 5.71178C4.31388 5.15501 4.97558 4.71364 5.70373 4.41295C6.43189 4.11226 7.21221 3.95817 8 3.95948H16C19.313 3.95948 22 6.65448 22 9.95348V21.9595H8C4.687 21.9595 2 19.2645 2 15.9655V9.95348ZM14 11.9595V13.9595H16V11.9595H14ZM8 11.9595V13.9595H10V11.9595H8Z" fill="white"/>
                        </g>
                        </g>
                        <defs>
                        <clipPath id="clip0_2_1638">
                        <rect width="24" height="24" fill="white" transform="translate(0 0.959473)"/>
                        </clipPath>
                        </defs>
                    </svg>                            
                </div>
                <div class="text-white text-2xl font-medium font-['Poppins']">
                    <a class="clickEvent" href="{% url 'chat_app:chat' %}" name="navbarMainPage">
                        닥터에게 질문하기
                    </a>
                </div>
            </div>
            <div class="self-stretch h-80 flex-col justify-start items-start gap-9 flex">
                <div class="justify-start items-start gap-2.5 inline-flex">
                    <a class="clickEvent flex items-center gap-2.5" href="{% url 'api_app:map' %}" name="navbarMap">
                        <div class="w-6 h-6 flex justify-center items-center">
                            <svg width="24" height="25" viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <g id="ri-group-2-fill" clip-path="url(#clip0_2_1645)">
                                <g id="Group">
                                <path id="Vector" d="M10 20.7075V17.3595C10 16.0765 10.995 15.0675 12.467 14.4915C11.5177 14.1384 10.5128 13.9582 9.5 13.9595C7.61 13.9595 5.864 14.5765 4.453 15.6195C4.89051 16.8568 5.62509 17.9678 6.59225 18.8549C7.55941 19.7421 8.72957 20.3782 10 20.7075ZM18.88 17.0455C18.485 16.5125 17.17 15.9595 15.5 15.9595C13.494 15.9595 12 16.7565 12 17.3595V20.9595C13.3878 20.9602 14.752 20.5998 15.9583 19.9135C17.1646 19.2273 18.1715 18.2388 18.88 17.0455ZM9.55 12.4595C10.1467 12.4595 10.719 12.2224 11.141 11.8005C11.5629 11.3785 11.8 10.8062 11.8 10.2095C11.8 9.61274 11.5629 9.04044 11.141 8.61848C10.719 8.19653 10.1467 7.95947 9.55 7.95947C8.95326 7.95947 8.38097 8.19653 7.95901 8.61848C7.53705 9.04044 7.3 9.61274 7.3 10.2095C7.3 10.8062 7.53705 11.3785 7.95901 11.8005C8.38097 12.2224 8.95326 12.4595 9.55 12.4595ZM15.5 13.4595C16.0304 13.4595 16.5391 13.2488 16.9142 12.8737C17.2893 12.4986 17.5 11.9899 17.5 11.4595C17.5 10.929 17.2893 10.4203 16.9142 10.0453C16.5391 9.67019 16.0304 9.45947 15.5 9.45947C14.9696 9.45947 14.4609 9.67019 14.0858 10.0453C13.7107 10.4203 13.5 10.929 13.5 11.4595C13.5 11.9899 13.7107 12.4986 14.0858 12.8737C14.4609 13.2488 14.9696 13.4595 15.5 13.4595ZM12 22.9595C6.477 22.9595 2 18.4825 2 12.9595C2 7.43647 6.477 2.95947 12 2.95947C17.523 2.95947 22 7.43647 22 12.9595C22 18.4825 17.523 22.9595 12 22.9595Z" fill="#001835"/>
                                </g>
                                </g>
                                <defs>
                                <clipPath id="clip0_2_1645">
                                <rect width="24" height="24" fill="white" transform="translate(0 0.959473)"/>
                                </clipPath>
                                </defs>
                            </svg>                                
                        </div>
                        <div class="text-slate-900 text-2xl font-medium font-['Poppins'] leading-normal">
                            병원/약국 찾기
                        </div>
                    </a>
                </div>
                <div class="justify-start items-start gap-2.5 inline-flex">
                    <a class="clickEvent flex items-center gap-2.5" href="{% url 'api_app:pedia' %}" name="navbarSearch">
                        <div class="w-6 h-6 flex justify-center items-center">
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <g id="ri-contacts-book-2-fill" clip-path="url(#clip0_2_1651)">
                                <g id="Group">
                                <path id="Vector" d="M20 22.9595H6C5.20435 22.9595 4.44129 22.6434 3.87868 22.0808C3.31607 21.5182 3 20.7551 3 19.9595V5.95947C3 5.16382 3.31607 4.40076 3.87868 3.83815C4.44129 3.27554 5.20435 2.95947 6 2.95947H20C20.2652 2.95947 20.5196 3.06483 20.7071 3.25237C20.8946 3.4399 21 3.69426 21 3.95947V21.9595C21 22.2247 20.8946 22.479 20.7071 22.6666C20.5196 22.8541 20.2652 22.9595 20 22.9595ZM19 20.9595V18.9595H6C5.73478 18.9595 5.48043 19.0648 5.29289 19.2524C5.10536 19.4399 5 19.6943 5 19.9595C5 20.2247 5.10536 20.479 5.29289 20.6666C5.48043 20.8541 5.73478 20.9595 6 20.9595H19ZM12 10.9595C12.5304 10.9595 13.0391 10.7488 13.4142 10.3737C13.7893 9.99861 14 9.48991 14 8.95947C14 8.42904 13.7893 7.92033 13.4142 7.54526C13.0391 7.17019 12.5304 6.95947 12 6.95947C11.4696 6.95947 10.9609 7.17019 10.5858 7.54526C10.2107 7.92033 10 8.42904 10 8.95947C10 9.48991 10.2107 9.99861 10.5858 10.3737C10.9609 10.7488 11.4696 10.9595 12 10.9595ZM9 14.9595H15C15 14.1638 14.6839 13.4008 14.1213 12.8382C13.5587 12.2755 12.7956 11.9595 12 11.9595C11.2044 11.9595 10.4413 12.2755 9.87868 12.8382C9.31607 13.4008 9 14.1638 9 14.9595Z" fill="#001835"/>
                                </g>
                                </g>
                                <defs>
                                <clipPath id="clip0_2_1651">
                                <rect width="24" height="24" fill="white" transform="translate(0 0.959473)"/>
                                </clipPath>
                                </defs>
                            </svg>                                
                        </div>
                        <div class="text-slate-900 text-2xl font-medium font-['Poppins'] leading-normal">
                            백과사전
                        </div>
                    </a>
                </div>
                <div class="justify-start items-start gap-2.5 inline-flex">
                    <a class="clickEvent flex items-center gap-2.5" href="{% url 'api_app:ask' %}" name="navbarAsk">
                        <div class="w-6 h-6 flex justify-center items-center">
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <g id="ri-phone-fill" clip-path="url(#clip0_2_1663)">
                                <g id="Group">
                                <path id="Vector" d="M21 17.3795V20.9155C21.0001 21.1686 20.9042 21.4124 20.7316 21.5977C20.559 21.7829 20.3226 21.8958 20.07 21.9135C19.633 21.9435 19.276 21.9595 19 21.9595C10.163 21.9595 3 14.7965 3 5.95947C3 5.68347 3.015 5.32647 3.046 4.88947C3.06372 4.63692 3.17658 4.40048 3.3618 4.22788C3.54703 4.05528 3.79082 3.95936 4.044 3.95947H7.58C7.70404 3.95935 7.8237 4.00533 7.91573 4.08849C8.00776 4.17165 8.0656 4.28606 8.078 4.40947C8.101 4.63947 8.122 4.82247 8.142 4.96147C8.34073 6.3484 8.748 7.69731 9.35 8.96247C9.445 9.16247 9.383 9.40147 9.203 9.52947L7.045 11.0715C8.36445 14.1459 10.8145 16.596 13.889 17.9155L15.429 15.7615C15.4919 15.6735 15.5838 15.6104 15.6885 15.5831C15.7932 15.5559 15.9042 15.5663 16.002 15.6125C17.267 16.2133 18.6156 16.6196 20.002 16.8175C20.141 16.8375 20.324 16.8595 20.552 16.8815C20.6752 16.8941 20.7894 16.952 20.8724 17.0441C20.9553 17.1361 21.0012 17.2556 21.001 17.3795H21Z" fill="#001835"/>
                                </g>
                                </g>
                                <defs>
                                <clipPath id="clip0_2_1663">
                                <rect width="24" height="24" fill="white" transform="translate(0 0.959473)"/>
                                </clipPath>
                                </defs>
                            </svg>                            
                        </div>
                        <div class="text-slate-900 text-2xl font-medium font-['Poppins'] leading-normal">
                            문의하기
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>